services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://f1user:f1password@db:5432/f1db
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=f1user
      - POSTGRES_PASSWORD=f1password
      - POSTGRES_DB=f1db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U f1user -d f1db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: